### ISSUE TITLE
8.0.8-beta1 vignette correction

### ISSUE THREAD

**Issue by FilipZamec** [mirsadm/motioncam#174] opened 2022-01-28 22:41 UTC
Thanks for the update.

Vignette correction fixes the vignette, but leaves the color shift intact on Mi 11 ultra, so I still get pinkish center.

**Comment by mirsadm** [comment] 2022-01-29 09:07
would you mind sharing a very short container file? that'll help me fix it

**Comment by FilipZamec** [comment] 2022-01-29 10:07
Sure. Here you go.
[https://drive.google.com/file/d/1UAs2qVVWkkD-6MO13vIwkzTPcFgsJhM1/view?usp=sharing](url)

**Comment by mirsadm** [comment] 2022-01-29 23:17
Could you make an uncropped recording and also take a DNG from your stock camera app please? I can't really reproduce this with my phone.

**Comment by FilipZamec** [comment] 2022-01-30 08:35
Hi, thanks for taking your time. You can't reproduce it, because most phones don't have color shift issue :( 
Anyway this is StockCamera DNG and Uncropped from MotionCam.
Thank you

[Stock DNG](https://drive.google.com/file/d/1UX6cnMYAQaFXKkZgoT52AlEK6df9fQ1S/view?usp=sharing)
[MotionCam uncropped](https://drive.google.com/file/d/1UvbJA08amEK_9vrahy_AbWaijgidVW_M/view?usp=sharing)

**Comment by mirsadm** [comment] 2022-01-30 16:08
Is it something that happens with other apps as well? If it's just MotionCam that'll be good since it's something I can fix

**Comment by FilipZamec** [comment] 2022-01-30 18:01
Ok, made some tests and here it is.
Stock cam takes the same dngs as Open camera or Freedcam, They have size always over 20 MB. 
MotionCam has sizes from 4 MB to 11 MB depending on the scene. I don't know if it matters.

But if I open Open Camera DNG in Photoshop, it removes vignette and color shift. 
If I do the same with Motion Cam DNG, it removes the vignette, but not the color shift. 

Also this is what it looks like after vignette correction in Open Camera:
![obrazek](https://user-images.githubusercontent.com/34546948/151711346-57d40613-921f-4949-b489-d8a40c0c845e.png)

and this is what it looks like in MotionCam:
![obrazek](https://user-images.githubusercontent.com/34546948/151711386-428f02d9-deb0-416c-b35a-5c456138b775.png)
There is this pinkish center.

All files can be found here:
[files](https://drive.google.com/drive/folders/15_QHZkQwsKZZLu6vXE5DSGA2B979fQ-C?usp=sharing)


Thank you...

**Comment by mirsadm** [comment] 2022-01-30 20:33
Ok figured this one out. The bayer arrangement on your phone is GBRG and the two green channels were in the wrong order. Will put out a fix soon.

**Comment by FilipZamec** [comment] 2022-01-30 20:48
You're a star 🌟

**Comment by mirsadm** [comment] 2022-02-04 16:04
Finally updated. Check out the new tools/app, should fix this at last.

**Comment by FilipZamec** [comment] 2022-02-05 12:49
Thank you Mirsad.
Color shift is finally gone. Even from uncorrected vignette 👍
But now it seems that Highlight Recovery in Davinci does absolutely nothing and it seems like I lost Dynamic Range. Will test it further...

**Comment by experimentator1709** [comment] 2022-02-05 12:56
@FilipZamec 
exposure up :)

**Comment by FilipZamec** [comment] 2022-02-05 13:04
After corrected exposure I still have blown out highlights which can't be recovered. In previous versions it was recoverable. 
I will check it later what's changed...

**Comment by mirsadm** [comment] 2022-02-05 17:00
I think I can fix this one. Looks like the correct range of pixels is not restored so it doesn't think it's clipped.

**Comment by FilipZamec** [comment] 2022-02-05 17:27
You are right :)
This is old version.
NotRecovered
![NotRecovered](https://user-images.githubusercontent.com/34546948/152652069-13de4087-ebc5-4f90-bdb6-3696c1f07307.png)

And recovered
![Recovered](https://user-images.githubusercontent.com/34546948/152652084-4208eda1-2854-482e-a923-2bf5da4ab367.png)

Now it looks always like not recovered...

Thank you, appreciate your work. Tell us finally how we can donate to your wonderful project :)

**Comment by mirsadm** [comment] 2022-03-17 21:54
@FilipZamec this has finally been fixed in the new beta

**Closed by mirsadm** 2022-03-17 21:54 UTC
